#!/bin/sh
#SBATCH --job-name=simu
#SBATCH -o simu.out
#SBATCH -e simu.err
#SBATCH --mem-per-cpu=50G

module load snakemake/5.3.0
module load bcftools
module load r/
module load python/3.9

snakemake --unlock --snakefile snakefile
snakemake --snakefile snakefile --cluster "sbatch -A abc_fish -c 1 -o log.out -e log.err --time=24:00:00" -j 50 -k

#for i in LG1A LG5 LG13 LG6 LG4 LG15 LG11 LG20 LG17 LG8 LG22-25 LG19 LG9 LG12 LG10 LG16 LGx LG1B LG24 LG3 MT LG18-21
#for i in LG1A
#for i in LG19 LG9 LG12 LG10 LG16 LGx LG1B LG24 LG3 MT LG18-21
#do
#	#echo $i
#	#echo Dlabr_$i
#	#INT=$(tail -n1 data/Dlabr_phased_${i}_AA_remove_fake_AA.vcf | awk '{print $2+1}')
#	#sed '5 i ##contig=<ID='$i',length='$INT'>' data/Dlabr_phased_${i}_AA_remove_fake_AA.vcf > data/Dlabr_phased_${i}_AA_remove_fake_AA_header.vcf
#	python3 /shared/projects/abc_fish/tree_topology/script/tsinfer_create_input_files.py /shared/projects/abc_fish/tree_topology/data/Dlabr_phased_${i}_AA_remove_fake_AA_header.vcf /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}.samples
#	python3 /shared/projects/abc_fish/tree_topology/script/tsinfer_infer.py /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}.samples 1e-8 1 /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}_1e-8_1.trees
#	python3 /shared/projects/abc_fish/tree_topology/script/tsdate_infer.py /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}_1e-8_1.trees 20 92500 1e-8 /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}_20_dated.trees /shared/projects/abc_fish/tree_topology/output/Dlabr_${i}_20_data.zip
#	#python3 /shared/projects/abc_fish/tree_topology/script/tsdate_infer.py /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1e-8_1.trees 200 92500 1e-8 /shared/projects/abc_fish/tree_topology/Dlabr_LG7_200_dated.trees /shared/projects/abc_fish/tree_topology/Dlabr_LG7_200_data.zip
#	#python3 /shared/projects/abc_fish/tree_topology/script/tsdate_infer.py /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1e-8_1.trees 500 92500 1e-8 /shared/projects/abc_fish/tree_topology/Dlabr_LG7_500_dated.trees /shared/projects/abc_fish/tree_topology/Dlabr_LG7_500_data.zip
#	#python3 /shared/projects/abc_fish/tree_topology/script/tsdate_infer.py /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1e-8_1.trees 1000 92500 1e-8 /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1000_dated.trees /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1000_data.zip
#	#python3 /shared/projects/abc_fish/tree_topology/script/tsdate_infer.py /shared/projects/abc_fish/tree_topology/Dlabr_LG7_1e-8_1.trees 2000 92500 1e-8 /shared/projects/abc_fish/tree_topology/Dlabr_LG7_2000_dated.trees /shared/projects/abc_fish/tree_topology/Dlabr_LG7_2000_data.zip
#done
